### ISSUE TITLE
パラメータ文字化けの件

### ISSUE THREAD

**Issue by milmilmi** [milmilmi/subject#1]
文字化け変換ツールなるもので調べました。
![image](https://user-images.githubusercontent.com/18700030/31569836-29185c64-b0b9-11e7-916e-be5d41172c94.png)
やっぱどっかで文字コード書き変わったな…git連携あたりが怪しいけど。

**Comment by milmilmi** [comment]
web.xmlで文字化けは解消しました

ですが
![image](https://user-images.githubusercontent.com/18700030/31569963-623d0408-b0ba-11e7-9cee-b431bf7f81fc.png)
こういう風に怒られるようになりました

**Comment by KeishiroOsaki** [comment]
なんか、GETリクエストで入力を投げてるっぽいですね
POSTで投げるようにすると直るかもしれません

**Comment by KeishiroOsaki** [comment]
POSTで投げるようにしてみましたが、同様のエラーが起きます。
色々と試していますが、緒をつかめずにいます。

**Comment by milmilmi** [comment]
contorollerのparamにスラッシュが付加されていたことが原因ぽいです。
ちゃんとコミットした最新の資産で修正をお願いしますよ。。
