### ISSUE TITLE
addに遷移するとプルダウンに変なのが追加される

### ISSUE THREAD

**Issue by milmilmi** [milmilmi/subject#4]
![image](https://user-images.githubusercontent.com/18700030/31655343-88bcd83c-b363-11e7-8d70-d2d8ded23f1a.png)
なんですかねこれ

**Comment by KeishiroOsaki** [comment]
Itemリスト用のリストに、明細に選択した項目を追加してしまうように誤って実装しておりました。
修正したので、本イシューをクローズします。
